language: csharp
mono:
- 4.6.2
os:
  - linux
  - osx
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential libssl-dev ; fi
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
- nvm install 4.3.0
- travis_retry npm install
- export DISPLAY=:99.0
- npm i -g xvfb-maybe
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sh -e /etc/init.d/xvfb start ;
  fi'
script:
- xvfb-maybe npm test
before_deploy:
- npm i -g babel-cli
- npm i -g electron-builder@5.26.0 ;
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get install -y wine ;
    sudo apt-get -qq update ;
    chmod +x ./scripts/builds/travis.sh ;
    "./scripts/builds/travis.sh" ;
  else
    cp ./scripts/builds/index.js ./src/js/pages/index.js ;
    babel src --out-dir src ;
    babel tC_apps --out-dir tC_apps ;
    build --mac ;
  fi'
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: vWCAoegCLLKDouMLDGUwb8P4CxcTynLYTtZH2CyEkru5Eucl9a9OPy16j0AxOQD1FxKWwbjCQ4MR4iISyNKPxZBwa9diGRjSQfV2ZqxsfaSECZTIYMFe6sMjPAnRSSnGz/0IAmsTJJMTSedNf8tM2fklODdwk2x/v4CGOjiIjcFpGgJ0iQFSt/K9CAjFhH4Ik7VKUwlcTQND0mXFZlTJKOsfZJgvp7zKdAGzB55V3uHJqLSjtDb70QYdSe4EWV/UVA+6R4bPr6+uxYJpggJD8dYo0As+G89fmscLucHqwKUs9qRyPkl4NdUlrcY+Xbr7jqEosUOnNJcLdfUjK57R04oAnRaVrz/iL2mHdosQlqFNn5RHa6u2FrHqRXAkb73fZqynnSeRq32s1Q2ysnCeHj6rYl078DuFm19zQ1cZxLK7EoM3BC54TPcZkQDUxkA301I36lJrxUdgt07AdEy4Dxsy5CcUvdsGbHeny/i80m2936uaRbaNg5uLmBswZScRQta4Bw+gywYwdD68lG96B7mPe9rz3Z2YXN1awH/0tyAztDsIxKQzx4TIFzYMVsgx7yb9r2xf4c5Vz56kr2NOZHym0fc/k1LGbC5Fc11lNhQ6IwU+psjl80Y5oacioVszsQ14+Ab/BavX5uk2sHeMQ/3zgfhB9twqt8dgsXXOYbI=
  file: "./dist/translationCore-win32-ia32/installer/translationCoreSetup.exe"
  on:
    repo: unfoldingWord-dev/translationCore
    branch: master
    tags: true
    condition: "$TRAVIS_OS_NAME == linux"
- provider: releases
  skip_cleanup: true
  api_key:
    secure: vWCAoegCLLKDouMLDGUwb8P4CxcTynLYTtZH2CyEkru5Eucl9a9OPy16j0AxOQD1FxKWwbjCQ4MR4iISyNKPxZBwa9diGRjSQfV2ZqxsfaSECZTIYMFe6sMjPAnRSSnGz/0IAmsTJJMTSedNf8tM2fklODdwk2x/v4CGOjiIjcFpGgJ0iQFSt/K9CAjFhH4Ik7VKUwlcTQND0mXFZlTJKOsfZJgvp7zKdAGzB55V3uHJqLSjtDb70QYdSe4EWV/UVA+6R4bPr6+uxYJpggJD8dYo0As+G89fmscLucHqwKUs9qRyPkl4NdUlrcY+Xbr7jqEosUOnNJcLdfUjK57R04oAnRaVrz/iL2mHdosQlqFNn5RHa6u2FrHqRXAkb73fZqynnSeRq32s1Q2ysnCeHj6rYl078DuFm19zQ1cZxLK7EoM3BC54TPcZkQDUxkA301I36lJrxUdgt07AdEy4Dxsy5CcUvdsGbHeny/i80m2936uaRbaNg5uLmBswZScRQta4Bw+gywYwdD68lG96B7mPe9rz3Z2YXN1awH/0tyAztDsIxKQzx4TIFzYMVsgx7yb9r2xf4c5Vz56kr2NOZHym0fc/k1LGbC5Fc11lNhQ6IwU+psjl80Y5oacioVszsQ14+Ab/BavX5uk2sHeMQ/3zgfhB9twqt8dgsXXOYbI=
  file_glob: true
  file: "./dist/mac/translationCore-*.dmg"
  on:
    repo: unfoldingWord-dev/translationCore
    branch: master
    tags: true
    condition: "$TRAVIS_OS_NAME == osx"
before_install:
- openssl aes-256-cbc -K $encrypted_23522de69895_key -iv $encrypted_23522de69895_iv
  -in Auth.json.enc -out Auth.json -d
